---
title: Jad Toghuj
timezone: JO
collections:
  social-media-and-content-creation:
    title: Social Media & Content Creation
    output: true
    permalink: "/:collection/:path/"
  styling-and-creative-direction:
    title: Styling & Creative Direction
    output: true
    permalink: "/:collection/:path/"
defaults:
- scope:
    path: ''
  values:
    layout: main
- scope:
    path: assets
  values:
    sitemap: false
baseurl:
url: https://jadtoghuj.com
description: Jad Toghuj | Editorial Stylist | Creative Director | Amman, Jordan
author: Jad Toghuj
email: jadtoghuj@gmail.com
instagram: "@jad.toghuj"
contact form action: https://formspree.io/f/mvovjwlo
footer text: By <a class="--no_border" href="https://basharalidreesi.com">Basabees</a>
  for <a class="--no_border" href="/">Batabeet</a>
plugins:
- jekyll-feed
- jekyll-sitemap
