---
title: Jad Toghuj
timezone: JO
collections:
  social-media-and-content-creation:
    title: Social Media & Content Creation
    output: true
    permalink: "/:collection/:path/"
  styling-and-creative-direction:
    title: Styling & Creative Direction
    output: true
    permalink: "/:collection/:path/"
defaults:
- scope:
    path: ""
  values:
    layout: main
- scope:
    path: assets
  values:
    sitemap: false
- scope:
    path: ""
    type: styling-and-creative-direction
  values:
    layout: project
- scope:
    path: ""
    type: social-media-and-content-creation
  values:
    layout: client
baseurl:
url: https://jadtoghuj.com
include:
- _*.apng
- _*.avif
- _*.gif
- _*.jpeg
- _*.jpg
- _*.png
- _*.svg
- _*.webp
- _*.bmp
- _*.ico
- _*.tiff
- _*.APNG
- _*.AVIF
- _*.GIF
- _*.JPEG
- _*.JPG
- _*.PNG
- _*.SVG
- _*.WEBP
- _*.BMP
- _*.ICO
- _*.TIFF
plugins:
- jekyll-feed
- jekyll-sitemap
