---
# Data
title: Jad Toghuj
author: Jad Toghuj
email: jadtoghuj@gmail.com
description: Jad Toghuj | Editorial Stylist | Creative Director | Amman, Jordan
baseurl: /
url: https://jadtoghuj.com
instagram: '@jad.toghuj'
timezone: JO
notice:
footer text: By <a class="--no_border" href="https://basharalidreesi.com">Basabees</a>
  for <a class="--no_border" href="/">Batabeet</a>

# Build
collections:
  social-media-and-content-creation:
    title: Social Media & Content Creation
    output: true
  styling-and-creative-direction:
    title: Styling & Creative Direction
    output: true
defaults:
  - scope:
      path: ''
    values:
      layout: main
  - scope:
      path: ''
      type: 'styling-and-creative-direction'
    values:
      layout: work
  - scope:
      path: ''
      type: 'social-media-and-content-creation'
    values:
      layout: work
theme: null
sass:
  sass_dir: _sass
  style: compact
  sourcemap: never
plugins:
- jekyll-feed
- jekyll-sitemap
