---
title: Jad Toghuj
timezone: JO
collections:
  social-media-and-content-creation:
    title: Social Media & Content Creation
    output: true
    permalink: "/:collection/:path/"
  styling-and-creative-direction:
    title: Styling & Creative Direction
    output: true
    permalink: "/:collection/:path/"
defaults:
- scope:
    path: ''
  values:
    layout: main
- scope:
    path: assets
  values:
    sitemap: false
baseurl:
url: https://jadtoghuj.com
plugins:
- jekyll-feed
- jekyll-sitemap
