---
new_page_extension: html
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Pages
- type: document
  path: about/index.html
  label: About
- type: directory
  path: _styling-and-creative-direction
  label: Styling & Creative Direction
  create: documents
  match: "**/*"
  new_doc_ext: html
  templates:
  - project
- type: directory
  path: _social-media-and-content-creation
  label: Social Media & Content Creation
  create: documents
  match: "**/*"
  new_doc_ext: html
  templates:
  - client
- type: heading
  label: Management
- type: document
  path: _data/homepageShowcase.yml
  label: Homepage Showcase
- type: document
  path: _data/projectDirectory.yml
  label: Project Directory
- type: document
  path: _data/clientDirectory.yml
  label: Client Directory
- type: heading
  label: Configuration
- type: document
  path: _data/generalConfiguration.yml
  label: General
- type: document
  path: _data/colors.yml
  label: Colors
upload_dir: assets/graphics
public_path: "/assets/graphics"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
