---
label: Project
hide_body: true
fields: []
pages:
- _styling-and-creative-direction/expertimenting-with-christina.html
- _styling-and-creative-direction/ghada-el-tally-for-pandora.html
- _styling-and-creative-direction/idreesi-and-abdulla-for-mykali.html
- _styling-and-creative-direction/with-a-bang.html
